# Generated by Django 3.2.5 on 2021-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210806_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, help_text='enter national code', max_length=10, null=True, unique=True, verbose_name='national code'),
        ),
    ]
