# Generated by Django 3.2.5 on 2021-08-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('subject', models.CharField(help_text='enter message subject here', max_length=50, verbose_name='subject')),
                ('customer_name', models.CharField(help_text='enter your name here', max_length=50, verbose_name='customer name')),
                ('phone_number', models.CharField(help_text='enter your phone number here', max_length=11, verbose_name='phone number')),
                ('email', models.CharField(help_text='enter your email here', max_length=50, verbose_name='email')),
                ('message_text', models.TextField(help_text='enter your message here', max_length=300, verbose_name='message text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
