# Generated by Django 3.2.5 on 2021-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(help_text='enter your message here', max_length=200, verbose_name='message text'),
        ),
    ]
