# Generated by Django 3.2.5 on 2021-08-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210806_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default='NEW', max_length=25, verbose_name='address title'),
        ),
    ]
