# Generated by Django 3.2.5 on 2021-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_customer_address_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='rest_of_address',
            field=models.TextField(blank=True, help_text='enter rest of address', verbose_name='rest of address'),
        ),
    ]
