# Generated by Django 3.2.5 on 2021-08-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_address_rest_of_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, help_text='enter latitude', null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, help_text='enter longitude', null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(default='NEW', help_text='enter title for this address', max_length=25, verbose_name='address title'),
        ),
    ]
