# Generated by Django 3.2.5 on 2021-08-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_address_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(default='New', help_text='enter title for this address', max_length=25, verbose_name='address title'),
        ),
    ]
