# Generated by Django 3.2.5 on 2021-08-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_address_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='specify customer', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='customer name'),
        ),
    ]
