# Generated by Django 3.2.5 on 2021-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20210820_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(blank=True, default='customer/images/customer.jpeg', help_text='upload your image', null=True, upload_to='customer/images/', verbose_name='customer image'),
        ),
    ]
