# Generated by Django 3.2.5 on 2021-08-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(help_text='enter name in english', max_length=30, verbose_name='english name')),
                ('name_fa', models.CharField(help_text='enter name in farsi', max_length=30, verbose_name='farsi name')),
                ('image', models.FileField(blank=True, help_text='upload image of category', null=True, upload_to='product/category/images/', verbose_name='category image')),
                ('ref_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('%', 'percent'), ('$', 'cash')], help_text='specify type of discount', max_length=15, verbose_name='discount type')),
                ('value', models.IntegerField(blank=True, default=0, help_text='specify discount value', null=True, verbose_name='discount value')),
                ('max_value', models.IntegerField(blank=True, help_text='specify maximum value', null=True, verbose_name='maximum value')),
                ('start_time', models.DateField(help_text='specify start time', verbose_name='discount start time')),
                ('expire_time', models.DateField(help_text='specify expire time', verbose_name='discount expire time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(help_text='enter name in english', max_length=50, verbose_name='english name')),
                ('name_fa', models.CharField(help_text='enter name in farsi', max_length=50, verbose_name='farsi name')),
                ('company_brand', models.CharField(help_text='enter company brand name in english', max_length=30, verbose_name='english company brand')),
                ('company_brand_fa', models.CharField(help_text='enter company brand name in farsi', max_length=30, verbose_name='farsi company brand')),
                ('price', models.IntegerField(help_text='enter price', verbose_name='price')),
                ('inventory', models.IntegerField(help_text='specify product inventory', verbose_name='inventory')),
                ('image', models.FileField(blank=True, help_text='upload image of product', null=True, upload_to='product/images/', verbose_name='product image')),
                ('specifications', models.CharField(blank=True, help_text='enter product specifications in english', max_length=100, null=True, verbose_name='english product specifications')),
                ('specifications_fa', models.CharField(blank=True, help_text='enter product specifications in farsi', max_length=100, null=True, verbose_name='farsi product specifications')),
                ('category', models.ForeignKey(help_text='specify category', on_delete=django.db.models.deletion.RESTRICT, to='product.category', verbose_name='category')),
                ('discount', models.ForeignKey(help_text='specify discount', on_delete=models.SET(0), to='product.discount', verbose_name='discount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
