# Generated by Django 3.2.5 on 2021-08-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210804_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ref_category',
        ),
        migrations.AddField(
            model_name='category',
            name='ref_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category'),
        ),
    ]
