# Generated by Django 3.2.5 on 2021-08-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, help_text='upload image of product', null=True, upload_to='product/images/', verbose_name='product image'),
        ),
    ]
