# Generated by Django 3.2.5 on 2021-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210804_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.IntegerField(default=0, help_text='specify level of self relation', verbose_name='category level'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company_brand_fa',
            field=models.CharField(blank=True, help_text='enter company brand name in farsi', max_length=30, null=True, verbose_name='farsi company brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fa',
            field=models.CharField(blank=True, help_text='enter name in farsi', max_length=50, null=True, verbose_name='farsi name'),
        ),
    ]
