# Generated by Django 3.2.5 on 2021-08-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210802_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, help_text='upload image of category', null=True, upload_to='category/images/', verbose_name='category image'),
        ),
    ]
