# Generated by Django 3.2.5 on 2021-08-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210805_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(blank=True, default=0, editable=False, help_text='specify level of self relation', null=True, verbose_name='category level'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ref_category',
            field=models.ForeignKey(blank=True, help_text='specify parent category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delete_timestamp',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
