# Generated by Django 3.2.5 on 2021-08-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210806_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_brand_fa',
            field=models.CharField(help_text='enter company brand name in farsi', max_length=30, verbose_name='farsi company brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fa',
            field=models.CharField(help_text='enter name in farsi', max_length=50, verbose_name='farsi name'),
        ),
    ]
