# Generated by Django 3.2.5 on 2021-08-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210809_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='product/category/images/category.jpeg', help_text='upload image of category', null=True, upload_to='product/category/images/', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='product/images/default.jpeg', help_text='upload image of product', null=True, upload_to='product/images/', verbose_name='product image'),
        ),
    ]
