# Generated by Django 3.2.5 on 2021-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='product/images/product.jpeg', help_text='upload image of product', null=True, upload_to='product/images/', verbose_name='product image'),
        ),
    ]
