# Generated by Django 3.2.5 on 2021-08-05 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_auto_20210806_0204'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('customer', models.OneToOneField(help_text='specify owner customer for cart', on_delete=django.db.models.deletion.RESTRICT, to='customer.customer', verbose_name='customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('modify_timestamp', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('product_number', models.IntegerField(default=1, help_text='specify number of selected product', verbose_name='numbers')),
                ('cart', models.ForeignKey(help_text='specify cart', on_delete=django.db.models.deletion.CASCADE, to='order.cart', verbose_name='cart')),
                ('product', models.ForeignKey(help_text='select product for add to your Cart', on_delete=django.db.models.deletion.RESTRICT, to='product.product', verbose_name='selected product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
