# Generated by Django 3.2.5 on 2021-08-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_address_owner'),
        ('product', '0005_auto_20210806_0204'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(help_text='specify owner customer for cart', on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(help_text='specify cart', on_delete=django.db.models.deletion.PROTECT, to='order.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='select product for add to your Cart', on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='selected product'),
        ),
    ]
