# Generated by Django 3.2.5 on 2021-08-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210814_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('WA', 'waiting'), ('FI', 'final cart'), ('PD', 'paid')], default='WA', help_text='display cart status', max_length=20, verbose_name='cart status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='specify cart', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_orderitems', related_query_name='customer_cart_orderitems', to='order.cart', verbose_name='cart'),
        ),
    ]
