# Generated by Django 3.2.5 on 2021-08-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_address_owner'),
        ('order', '0006_auto_20210816_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(help_text='specify owner customer for cart', on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('WA', 'waiting'), ('PD', 'paid')], default='WA', help_text='display cart status', max_length=20, verbose_name='cart status'),
        ),
    ]
