# Generated by Django 3.2.5 on 2021-08-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_address_owner'),
        ('order', '0008_cart_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_address',
            field=models.ForeignKey(blank=True, help_text='specify address for send order', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.address', verbose_name='customer address'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='specify owner customer for cart', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='customer'),
        ),
    ]
