# Generated by Django 3.2.5 on 2021-08-18 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210809_0003'),
        ('order', '0010_alter_cart_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='specify cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_orderitems', related_query_name='customer_cart_orderitems', to='order.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='select product for add to your Cart', on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='selected product'),
        ),
    ]
