# Generated by Django 3.2.5 on 2021-08-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_cart_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.IntegerField(blank=True, help_text='final cart price', null=True, verbose_name='final price'),
        ),
    ]
